version: "3"
services:
  api-server:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ~/go:/go
    environment:
      MYSQL_HOST:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DB:
  mobile:
    build:
      context: ./mobile
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./mobile:/app
